import fs from "fs-extra";
import path from "node:path";

const CONFIG_NAME = "rendershield.config.json";

const DEFAULT_CONFIG = {
  version: 1,
  site: {
    canonicalBase: "https://example.com",
    siteName: "Example Site",
    defaultOgImage: "https://example.com/og/default.jpg",
    authorName: "Your Name"
  },
  content: {
    markdown: {
      baseDir: "content",
      collections: [
        {
          name: "blog",
          pattern: "blog/**/*.md",
          routeBase: "/blog",
          schemaType: "Article"
        }
      ]
    }
  },
  output: {
    outDir: "dist-prerender",
    prettyHtml: true
  },
  sitemap: {
    enabled: true,
    path: "/sitemap.xml"
  },
  robots: {
    enabled: true,
    path: "/robots.txt"
  },
  worker: {
    enabled: true,
    lovableOrigin: "https://YOUR_SITE.lovable.app",
    rewriteRouteBases: ["/blog/"],
    botUserAgentPatterns: [
      "googlebot",
      "bingbot",
      "gptbot",
      "claudebot",
      "perplexitybot",
      "twitterbot",
      "facebookexternalhit",
      "linkedinbot",
      "slackbot",
      "discordbot",
      "whatsapp",
      "telegram"
    ],
    debugHeaders: true
  }
};

const today = new Date().toISOString().slice(0, 10);

const SAMPLE_POST = `---
title: Hello World
excerpt: This is a sample post generated by RenderShield.
datePublished: ${today}
coverImage: /images/blog/hello.jpg
slug: hello-world
---

This is **RenderShield**.

- Bots should see real HTML.
- Humans keep the SPA.

That's the whole trick.
`;

export async function cmdInit(cwd = process.cwd()) {
  const configPath = path.join(cwd, CONFIG_NAME);
  const contentDir = path.join(cwd, "content", "blog");
  const samplePath = path.join(contentDir, "hello-world.md");

  const configExists = await fs.pathExists(configPath);
  if (!configExists) {
    await fs.writeFile(configPath, JSON.stringify(DEFAULT_CONFIG, null, 2) + "\n", "utf8");
    console.log(`Created ${CONFIG_NAME}`);
  } else {
    console.log(`${CONFIG_NAME} already exists (leaving it alone)`);
  }

  await fs.ensureDir(contentDir);

  const sampleExists = await fs.pathExists(samplePath);
  if (!sampleExists) {
    await fs.writeFile(samplePath, SAMPLE_POST, "utf8");
    console.log(`Created sample content: content/blog/hello-world.md`);
  } else {
    console.log(`Sample content already exists (leaving it alone)`);
  }

  console.log(`
Next:
  1) Edit rendershield.config.json
  2) Add posts under content/blog/
  3) Run: rendershield build
`);
}
